### ISSUE TITLE
Unable to identify the Modal close button (when testing with Cypress and tracking with Pendo)

### ISSUE THREAD

**Issue by derekhawker** [cheton/styled-ui#684]
Hi, having some trouble with an issue and wanted to see if someone had some better ideas. I'm trying to do two things:

- I want to write a Cypress test for a user flow that includes closing a modal. 
- And, I would like to set up some analytics in Pendo that detect when users bypass certain processes by clicking the close button on a modal.

It's tricky for me as I would usually attach a data-* attribute on the button to use for both situation. But there isn't really a way to do this because the close button is added to the Modal by Tonic itself. I don't have a way of setting the data-* attribute

I've tried working around it. For testing I search for the last button element inside the the Modal container. This works since the close button is added after the Header, Body, and Footer component. It does feel a little risky as it could easily break if the Modal component is refactored. 

And this approach doesn't work for Pendo. In there I ended up having to use the Pendo JS API to manually send events whenever the modal closes. This isn't ideal as I'd prefer all this is done by making changes using just the Pendo GUI tools.

Sorry if this was a bit lengthy.  I think the best approach for me would be If I could attach custom attributes to the Modal close button. **Is there a way to do this reliably?** Would there be interest in supporting a way to do this as one of the Modal configuration props? Maybe a way to pass a custom CloseButton component?

**Update Feb.8**:
There's a similar issue regarding tracking when an Alert's close button is clicked

**Comment by cheton** [comment]
Hi @derekhawker,

A better approach is to add class names to all components. However, it does require significant time and effort to properly name and test each class. 

As a temporary solution, you can add the `ModalCloseButton` component manually to the modal component, rather than relying on the `isClosable` prop. This way, you can have control over the close button and attach custom attributes to it as needed. Here's an example of how to do this:

```js
import { ModalCloseButton } from '@tonic-ui/react';
```


In this example, you can add the `data-test` attribute to the `ModalCloseButton` component, and access it in your tests or data tracking as needed.

```jsx
<Modal
  isOpen={isOpen}
  onClose={closeModal}
>
  <ModalOverlay />
  <ModalContent>
    <ModalHeader>
      Header
    </ModalHeader>
    <ModalCloseButton onClick={closeModal} data-test="tonic-modal__close-button" />
    <ModalBody>
      Body
    </ModalBody>
    <ModalFooter>
      Footer
    </ModalFooter>
  </ModalContent>
</Modal>
```

I will also make a change to the `ModalCloseButton` component to handle the `onClick` event in the next release, so you don't have to do it manually in the future.

Let me know if this helps, or if you have any further questions.

**Comment by derekhawker** [comment]
Not sure about the classname suggestion. Usually avoid that since it's pretty easy for those to be hashed/uglified during the build process. The second suggestion would work quite nicely though. 

For alerts it looks like the implementation is slightly more complicated, but basically the same idea. ~Do you think AlertCloseButton will be refactored at some point to move the Icon inside to match the CloseButton components in Modals and Drawer?~ EDIT: You're way ahead of me. Saw you did just that in your PR. Thanks for the speedy update

```
<Alert severity="info" onClose={handleClose}>
  <Flex justifyContent="space-between">
    <Box>{alertMessage}</Box>
    <AlertCloseButton data-test="tonic-alert__close-button"/>
  </Flex>
</Alert>
```
